# -*- coding: utf-8 -*-
"""regression_finally.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bIZ5cPLkGDC00_MZpuiqmVGqOcIJV230
"""

from pathlib import Path
import sys

import pandas as pd
import numpy as np
import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

import warnings
warnings.filterwarnings("ignore")

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = PROJECT_ROOT / "data" / "seoul_tourism_2020_2024_clean_common.csv"
FIGURE_DIR = PROJECT_ROOT / "outputs" / "figures"
TABLE_DIR = PROJECT_ROOT / "outputs" / "tables"

FIGURE_DIR.mkdir(parents=True, exist_ok=True)
TABLE_DIR.mkdir(parents=True, exist_ok=True)


def save_current_figure(filename):
    """Save the active matplotlib figure and close it."""
    output_path = FIGURE_DIR / filename
    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"Saved figure: {output_path.relative_to(PROJECT_ROOT)}")


# matplotlib 기본 설정
mpl.rcParams.update(mpl.rcParamsDefault)
mpl.rcParams["axes.unicode_minus"] = False

# =============================================================================
# 1. 데이터 로드 및 기본 정보
# =============================================================================

try:
    df = pd.read_csv(DATA_PATH)
except FileNotFoundError:
    raise FileNotFoundError(f"CSV 파일을 찾을 수 없습니다: {DATA_PATH}")

df["date"] = pd.to_datetime(df["date"])
df = df.sort_values("date").reset_index(drop=True)

# 시간 파생변수
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day_of_year"] = df["date"].dt.dayofyear

print("="*80)
print("1. 데이터 로드 및 기본 정보")
print("="*80)
print(f"원본 데이터 shape: {df.shape}")
print(f"날짜 범위: {df['date'].min()} ~ {df['date'].max()}")
print("연도별 데이터 개수:")
print(df["year"].value_counts().sort_index(), "\n")

# =============================================================================
# 2. EDA – 타깃 분포, 시계열 추이, 상관관계
# =============================================================================

print("="*80)
print("2. EDA - 타깃 분포, 시계열 추이, 상관관계")
print("="*80)

y = df["daily_visitors"].values
y_log = np.log1p(y)

fig, axes = plt.subplots(1, 3, figsize=(16, 4))
axes[0].hist(y, bins=50, edgecolor="black")
axes[0].set_title("Visitor count distribution (original)")
axes[0].set_xlabel("daily_visitors")
axes[0].set_ylabel("Frequency")

axes[1].hist(y_log, bins=50, edgecolor="black")
axes[1].set_title("Visitor count distribution (log1p transformed)")
axes[1].set_xlabel("log1p(daily_visitors)")

axes[2].boxplot(y)
axes[2].set_title("Visitor count boxplot")
axes[2].set_ylabel("daily_visitors")

plt.tight_layout()
save_current_figure("target_distribution.png")

print("타깃(daily_visitors) 통계:")
print(f"  평균: {y.mean():,.1f}")
print(f"  중앙값: {np.median(y):,.1f}")
print(f"  표준편차: {y.std():,.1f}")
print(f"  왜도(Skewness, 원본): {pd.Series(y).skew():.2f}")
print(f"  왜도(Skewness, log1p): {pd.Series(y_log).skew():.2f}\n")

# 전체 일별 방문객 시계열(POI 합산)
daily_agg = df.groupby("date")["daily_visitors"].sum()
plt.figure(figsize=(14, 4))
plt.plot(daily_agg.index, daily_agg.values, linewidth=0.7)
plt.title("Daily total visitors over time (all POIs)")
plt.xlabel("Date")
plt.ylabel("Visitors")
plt.grid(alpha=0.3)
plt.tight_layout()
save_current_figure("daily_total_visitors.png")

# 상관관계
numeric_cols_for_corr = [
    "temp", "humidity", "precip", "pm25", "TCI",
    "outdoor_ratio", "accessibility_score",
    "year", "month", "day_of_year",
    "daily_visitors"
]
existing_numeric = [c for c in numeric_cols_for_corr if c in df.columns]

if len(existing_numeric) > 1:
    corr = df[existing_numeric].corr()
    plt.figure(figsize=(10, 8))
    sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", center=0)
    plt.title("Correlation matrix of numeric features")
    plt.tight_layout()
    save_current_figure("correlation_matrix.png")

# =============================================================================
# 3. 모델링용 데이터 준비 (인코딩, 타깃 변환, 피처 선택)
# =============================================================================

print("="*80)
print("3. 모델링용 데이터 준비")
print("="*80)

df_model = df.copy()
df_model["target_log"] = np.log1p(df_model["daily_visitors"])

leakage_cols = ["foreign_visitors", "foreign_share", "crowd_level"]
existing_leakage_cols = [c for c in leakage_cols if c in df_model.columns]
if existing_leakage_cols:
    print(f"예측 시점에 알기 어려운 누수 위험 피처 제외: {existing_leakage_cols}")
    df_model = df_model.drop(columns=existing_leakage_cols)

# One-hot 인코딩
object_cols = df_model.select_dtypes(include=["object"]).columns.tolist()
categorical_cols = [c for c in object_cols if c not in ["date", "poi_id", "poi_name"]]
if categorical_cols:
    df_model = pd.get_dummies(df_model, columns=categorical_cols, drop_first=True)

# 타깃 결측 제거
df_model = df_model.dropna(subset=["daily_visitors", "target_log"])

# 완전 NaN 컬럼 0으로 대체
num_cols_all = df_model.select_dtypes(include=[np.number]).columns.tolist()
print("\n수치형 피처 결측치 처리 시작...")
for col in num_cols_all:
    if df_model[col].isnull().all():
        print(f"  - 경고: '{col}' 컬럼이 전체 NaN이어서 0으로 채웠습니다.")
        df_model[col] = 0.0

# 피처 선택
exclude_cols = ["date", "daily_visitors", "target_log"]
for col in ["poi_id", "poi_name"]:
    if col in df_model.columns:
        exclude_cols.append(col)

feature_cols = [c for c in df_model.columns if c not in exclude_cols]

print(f"사용 피처 개수: {len(feature_cols)}")
print(f"사용 피처 예시: {feature_cols[:10]}\n")

numeric_features = [c for c in feature_cols if pd.api.types.is_numeric_dtype(df_model[c])]

# =============================================================================
# 4. Train/Test 시계열 분할 (2020–2023 → Train, 2024 → Test)
# =============================================================================

print("="*80)
print("4. Train/Test 시계열 분할 (2020–2023 학습, 2024 테스트)")
print("="*80)

if "year" not in df_model.columns:
    raise ValueError("year 컬럼이 없습니다. 데이터 전처리를 확인하세요.")

train_mask = df_model["year"] <= 2023
test_mask = df_model["year"] == 2024

X_train = df_model.loc[train_mask, feature_cols].copy()
y_train = df_model.loc[train_mask, "daily_visitors"].copy()
y_train_log = df_model.loc[train_mask, "target_log"].copy()

X_test = df_model.loc[test_mask, feature_cols].copy()
y_test = df_model.loc[test_mask, "daily_visitors"].copy()
y_test_log = df_model.loc[test_mask, "target_log"].copy()

if X_test.empty:
    raise ValueError("2024년 테스트 데이터가 없습니다. year 컬럼 및 데이터 범위를 확인하세요.")

print(f"Train shape: {X_train.shape}, Test shape: {X_test.shape}")
print(f"Train 기간: {df_model.loc[train_mask, 'date'].min()} ~ {df_model.loc[train_mask, 'date'].max()}")
print(f"Test 기간 : {df_model.loc[test_mask, 'date'].min()} ~ {df_model.loc[test_mask, 'date'].max()}\n")

# =============================================================================
# 5. Imputation + Standardization
# =============================================================================

print("="*80)
print("5. Imputation 및 Standardization")
print("="*80)

if numeric_features:
    imputer = SimpleImputer(strategy="mean")
    X_train[numeric_features] = imputer.fit_transform(X_train[numeric_features])
    X_test[numeric_features] = imputer.transform(X_test[numeric_features])

scaler = StandardScaler()
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

if numeric_features:
    X_train_scaled[numeric_features] = scaler.fit_transform(X_train[numeric_features])
    X_test_scaled[numeric_features] = scaler.transform(X_test[numeric_features])
    print(f"표준화 대상 수치형 피처 수: {len(numeric_features)}\n")

# =============================================================================
# 6. Baseline 모델
# =============================================================================

print("="*80)
print("6. Baseline 모델 (Train 평균 예측)")
print("="*80)

baseline_mean = y_train.mean()
y_pred_baseline = np.full_like(y_test.values, baseline_mean, dtype=float)

baseline_mse = mean_squared_error(y_test, y_pred_baseline)
baseline_r2 = r2_score(y_test, y_pred_baseline)
baseline_mae = mean_absolute_error(y_test, y_pred_baseline)

print("Baseline (Train 평균값으로 모든 날짜 예측):")
print(f"  Test MSE: {baseline_mse:,.1f}")
print(f"  Test R² : {baseline_r2:.4f}")
print(f"  Test MAE: {baseline_mae:,.1f}\n")

# =============================================================================
# 7. 기본 회귀 모델 학습/평가 (RF는 여기서 1회 기본 성능)
# =============================================================================

print("="*80)
print("7. 회귀 모델 학습 및 평가 (RF 기본 포함)")
print("="*80)

models = {
    "Linear Regression": LinearRegression(),
    "Ridge (α=1.0)": Ridge(alpha=1.0),
    "LASSO (α=0.001)": Lasso(alpha=0.001, max_iter=10000),
    "Decision Tree (depth=5)": DecisionTreeRegressor(max_depth=5, random_state=42),
    "Random Forest (default)": RandomForestRegressor(
        n_estimators=200,
        max_depth=None,
        min_samples_split=10,
        random_state=42,
        n_jobs=-1
    )
}

results = {}
trained_models = {}

for name, model in models.items():
    print(f"\n[모델 학습] {name}")
    model.fit(X_train_scaled, y_train_log)
    trained_models[name] = model

    y_train_pred_log = model.predict(X_train_scaled)
    y_test_pred_log = model.predict(X_test_scaled)

    y_train_pred = np.expm1(y_train_pred_log)
    y_test_pred = np.expm1(y_test_pred_log)

    mse_train = mean_squared_error(y_train, y_train_pred)
    mse_test = mean_squared_error(y_test, y_test_pred)
    r2_train = r2_score(y_train, y_train_pred)
    r2_test = r2_score(y_test, y_test_pred)
    mae_test = mean_absolute_error(y_test, y_test_pred)

    results[name] = {
        "MSE_train": mse_train,
        "MSE_test": mse_test,
        "R2_train": r2_train,
        "R2_test": r2_test,
        "MAE_test": mae_test,
        "y_test_pred": y_test_pred
    }

    print(f"  MSE  (train): {mse_train:,.0f} | (test): {mse_test:,.0f}")
    print(f"  R²   (train): {r2_train:.4f} | (test): {r2_test:.4f}")
    print(f"  MAE  (test) : {mae_test:,.0f}")
    print(f"  Baseline 대비 MSE 개선율: {(baseline_mse - mse_test) / baseline_mse * 100:+.1f}%")

# =============================================================================
# 8. Polynomial Regression (degree=2)
# =============================================================================

print("\n" + "="*80)
print("8. Polynomial Regression (degree=2)")
print("="*80)

poly = PolynomialFeatures(degree=2, include_bias=False)
X_train_poly = poly.fit_transform(X_train_scaled)
X_test_poly = poly.transform(X_test_scaled)

poly_lr = LinearRegression()
poly_lr.fit(X_train_poly, y_train_log)

y_test_poly_pred_log = poly_lr.predict(X_test_poly)
y_test_poly_pred = np.expm1(y_test_poly_pred_log)

poly_mse_test = mean_squared_error(y_test, y_test_poly_pred)
poly_r2_test = r2_score(y_test, y_test_poly_pred)
poly_mae_test = mean_absolute_error(y_test, y_test_poly_pred)

results["Polynomial (degree=2)"] = {
    "MSE_train": mean_squared_error(y_train, np.expm1(poly_lr.predict(X_train_poly))),
    "MSE_test": poly_mse_test,
    "R2_train": r2_score(y_train, np.expm1(poly_lr.predict(X_train_poly))),
    "R2_test": poly_r2_test,
    "MAE_test": poly_mae_test,
    "y_test_pred": y_test_poly_pred
}

print(f"  Test MSE: {poly_mse_test:,.0f}")
print(f"  Test R² : {poly_r2_test:.4f}")
print(f"  Test MAE: {poly_mae_test:,.0f}")
print(f"  Baseline 대비 MSE 개선율: {(baseline_mse - poly_mse_test) / baseline_mse * 100:+.1f}%")

# =============================================================================
# 9. 모델 성능 비교 (기본 모델 기준)
# =============================================================================

print("\n" + "="*80)
print("9. 모델 성능 비교 (기본 모델, Test MSE 기준 정렬)")
print("="*80)

rows = []
rows.append(
    {
        "Model": "Baseline (Train mean)",
        "MSE_test": baseline_mse,
        "R2_test": baseline_r2,
        "MAE_test": baseline_mae
    }
)
for name, res in results.items():
    rows.append(
        {
            "Model": name,
            "MSE_test": res["MSE_test"],
            "R2_test": res["R2_test"],
            "MAE_test": res["MAE_test"]
        }
    )

metrics_df = pd.DataFrame(rows).sort_values("MSE_test").reset_index(drop=True)
print(metrics_df.to_string(index=False))
metrics_df.to_csv(TABLE_DIR / "model_comparison_basic.csv", index=False)

plt.figure(figsize=(10, 4))
plt.bar(metrics_df["Model"], metrics_df["MSE_test"])
plt.xticks(rotation=45, ha="right")
plt.ylabel("Test MSE")
plt.title("Model comparison (basic)")
plt.tight_layout()
save_current_figure("model_comparison_basic.png")

# =============================================================================
# 9-1. Random Forest Parameter Sweep (RandomizedSearchCV 제거 버전)
#      - RF 파라미터 조합 몇 개만 바꿔가며 결과를 표/그래프로 비교
# =============================================================================

print("\n" + "="*80)
print("9-1. Random Forest Parameter Sweep (simple comparison)")
print("="*80)

def train_eval_rf(params, Xtr, ytr_log, Xte, yte):
    """log 타깃으로 학습 -> expm1 복원 후 Test(원스케일)에서 평가"""
    rf = RandomForestRegressor(
        **params,
        random_state=42,
        n_jobs=-1
    )
    rf.fit(Xtr, ytr_log)
    pred_log = rf.predict(Xte)
    pred = np.expm1(pred_log)

    mse = mean_squared_error(yte, pred)
    mae = mean_absolute_error(yte, pred)
    r2  = r2_score(yte, pred)
    return rf, pred, mse, mae, r2

# 너무 복잡하지 않게, “움직이는 축만” 몇 개 조합으로 비교
rf_param_candidates = [
    {
        "name": "RF_A (baseline-ish)",
        "params": {"n_estimators": 200, "max_depth": None, "min_samples_split": 10, "min_samples_leaf": 5, "max_features": "sqrt"},
    },
    {
        "name": "RF_B (shallower)",
        "params": {"n_estimators": 300, "max_depth": 15, "min_samples_split": 10, "min_samples_leaf": 5, "max_features": "sqrt"},
    },
    {
        "name": "RF_C (deeper + small leaf)",
        "params": {"n_estimators": 300, "max_depth": None, "min_samples_split": 5, "min_samples_leaf": 1, "max_features": "sqrt"},
    },
    {
        "name": "RF_D (regularized leaf)",
        "params": {"n_estimators": 400, "max_depth": None, "min_samples_split": 10, "min_samples_leaf": 10, "max_features": "sqrt"},
    },
    {
        "name": "RF_E (more regularized)",
        "params": {"n_estimators": 400, "max_depth": 20, "min_samples_split": 20, "min_samples_leaf": 20, "max_features": "sqrt"},
    },
    {
        "name": "RF_F (max_features=0.5)",
        "params": {"n_estimators": 400, "max_depth": None, "min_samples_split": 10, "min_samples_leaf": 5, "max_features": 0.5},
    },
    {
        "name": "RF_G (max_features=0.7)",
        "params": {"n_estimators": 400, "max_depth": None, "min_samples_split": 10, "min_samples_leaf": 5, "max_features": 0.7},
    },
    {
        "name": "RF_H (depth=25)",
        "params": {"n_estimators": 500, "max_depth": 25, "min_samples_split": 10, "min_samples_leaf": 5, "max_features": "sqrt"},
    },
]

sweep_rows = []
sweep_models = {}

for cand in rf_param_candidates:
    name = cand["name"]
    params = cand["params"]

    print(f"\n[RF Sweep] {name} | params={params}")
    rf, pred, mse, mae, r2 = train_eval_rf(params, X_train_scaled, y_train_log, X_test_scaled, y_test)

    sweep_models[name] = {"model": rf, "y_test_pred": pred, "params": params}
    sweep_rows.append({
        "Model": name,
        "MSE_test": mse,
        "MAE_test": mae,
        "R2_test": r2,
        "n_estimators": params.get("n_estimators"),
        "max_depth": str(params.get("max_depth")),
        "min_samples_split": params.get("min_samples_split"),
        "min_samples_leaf": params.get("min_samples_leaf"),
        "max_features": str(params.get("max_features")),
    })

sweep_df = pd.DataFrame(sweep_rows).sort_values("MSE_test").reset_index(drop=True)

print("\n=== [Table] RF Parameter Sweep Results (sorted by Test MSE) ===")
print(sweep_df.to_string(index=False))
sweep_df.to_csv(TABLE_DIR / "rf_parameter_sweep.csv", index=False)

# 그래프 1: MSE 비교(수평 막대)
plt.figure(figsize=(10, 5))
plt.barh(sweep_df["Model"][::-1], sweep_df["MSE_test"][::-1])
plt.xlabel("Test MSE (original scale)")
plt.title("RF parameter sweep: Test MSE (lower is better)")
plt.tight_layout()
save_current_figure("rf_sweep_mse.png")

# 그래프 2: MAE 비교(수평 막대)
plt.figure(figsize=(10, 5))
plt.barh(sweep_df["Model"][::-1], sweep_df["MAE_test"][::-1])
plt.xlabel("Test MAE (original scale)")
plt.title("RF parameter sweep: Test MAE (lower is better)")
plt.tight_layout()
save_current_figure("rf_sweep_mae.png")

# (선택) 그래프 3: R2 비교(수평 막대)
plt.figure(figsize=(10, 5))
plt.barh(sweep_df["Model"][::-1], sweep_df["R2_test"][::-1])
plt.xlabel("Test R²")
plt.title("RF parameter sweep: Test R² (higher is better)")
plt.tight_layout()
save_current_figure("rf_sweep_r2.png")

# 스윕 중 Best 모델을 "RF (sweep_best)"로 등록
best_rf_name = sweep_df.iloc[0]["Model"]
best_rf = sweep_models[best_rf_name]["model"]
best_pred = sweep_models[best_rf_name]["y_test_pred"]

print("\n" + "-"*80)
print(f"> Best RF from sweep: {best_rf_name}")
print(f"> Best params: {sweep_models[best_rf_name]['params']}")
print(f"> Best Test MSE: {sweep_df.iloc[0]['MSE_test']:,.1f} | "
      f"MAE: {sweep_df.iloc[0]['MAE_test']:,.1f} | R2: {sweep_df.iloc[0]['R2_test']:.4f}")
print("-"*80)

results["Random Forest (sweep_best)"] = {
    "MSE_train": np.nan,
    "MSE_test": float(sweep_df.iloc[0]["MSE_test"]),
    "R2_train": np.nan,
    "R2_test": float(sweep_df.iloc[0]["R2_test"]),
    "MAE_test": float(sweep_df.iloc[0]["MAE_test"]),
    "y_test_pred": best_pred
}
trained_models["Random Forest (sweep_best)"] = best_rf

# =============================================================================
# 9-2. (업데이트) 모델 성능 비교 (RF sweep_best 포함)
# =============================================================================

print("\n" + "="*80)
print("9-2. 모델 성능 비교 (RF sweep_best 포함, Test MSE 기준 정렬)")
print("="*80)

rows2 = []
rows2.append(
    {
        "Model": "Baseline (Train mean)",
        "MSE_test": baseline_mse,
        "R2_test": baseline_r2,
        "MAE_test": baseline_mae
    }
)
for name, res in results.items():
    rows2.append(
        {
            "Model": name,
            "MSE_test": res["MSE_test"],
            "R2_test": res["R2_test"],
            "MAE_test": res["MAE_test"]
        }
    )

metrics_df2 = pd.DataFrame(rows2).sort_values("MSE_test").reset_index(drop=True)
print(metrics_df2.to_string(index=False))
metrics_df2.to_csv(TABLE_DIR / "model_comparison_with_rf_sweep.csv", index=False)

rf_model_names = [name for name in results if name.startswith("Random Forest")]
best_model_name = min(rf_model_names, key=lambda name: results[name]["MSE_test"])
print(f"\nBest Random Forest overall: {best_model_name}")

plt.figure(figsize=(10, 4))
plt.bar(metrics_df2["Model"], metrics_df2["MSE_test"])
plt.xticks(rotation=45, ha="right")
plt.ylabel("Test MSE")
plt.title("Model comparison (including RF sweep_best)")
plt.tight_layout()
save_current_figure("model_comparison_with_rf_sweep.png")

# =============================================================================
# 10. 잔차 분석 (Best Random Forest 기준)
# =============================================================================

print("\n" + "="*80)
print("10. 잔차 분석 (Best Random Forest 기준)")
print("="*80)

y_test_pred = results[best_model_name]["y_test_pred"]
residuals = y_test.values - y_test_pred

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].scatter(y_test.values, y_test_pred, alpha=0.4, edgecolor="white")
min_val = min(y_test.min(), y_test_pred.min())
max_val = max(y_test.max(), y_test_pred.max())
axes[0].plot([min_val, max_val], [min_val, max_val], linestyle="--", linewidth=2, label="y = x")
axes[0].set_xlabel("Actual visitors")
axes[0].set_ylabel("Predicted visitors")
axes[0].set_title(f"Actual vs Predicted ({best_model_name})")
axes[0].legend()
axes[0].grid(alpha=0.3)

axes[1].scatter(y_test_pred, residuals, alpha=0.4, edgecolor="white")
axes[1].axhline(y=0, linestyle="--", linewidth=2)
axes[1].set_xlabel("Predicted visitors")
axes[1].set_ylabel("Residuals (actual - predicted)")
axes[1].set_title("Residual plot")
axes[1].grid(alpha=0.3)

plt.tight_layout()
save_current_figure("actual_vs_predicted_and_residuals.png")

plt.figure(figsize=(6, 4))
plt.hist(residuals, bins=50, edgecolor="black")
plt.title("Residuals histogram")
plt.xlabel("Residual")
plt.ylabel("Frequency")
plt.tight_layout()
save_current_figure("residuals_histogram.png")

print("\n잔차 통계:")
print(pd.Series(residuals).describe())

abs_resid = np.abs(residuals)
top_idx = np.argsort(-abs_resid)[:10]

top_cases = pd.DataFrame({
    "date": df_model.loc[test_mask, "date"].reset_index(drop=True).iloc[top_idx].values,
    "actual": y_test.reset_index(drop=True).iloc[top_idx].values,
    "predicted": y_test_pred[top_idx],
    "residual": residuals[top_idx]
}).sort_values("residual", key=lambda x: np.abs(x), ascending=False)

print(f"\n=== [Table] Top 10 Cases with Largest Absolute Residuals ({best_model_name}) ===")
print(top_cases.to_string(index=False))
top_cases.to_csv(TABLE_DIR / "top_residual_cases.csv", index=False)

# =============================================================================
# 10-1. Best Random Forest Feature Importance (상위 10개)
# =============================================================================

rf = trained_models[best_model_name]
importances = rf.feature_importances_
feat_imp = pd.Series(importances, index=feature_cols).sort_values(ascending=False)

top_k = 10
feat_imp_top = feat_imp.head(top_k).reset_index()
feat_imp_top.columns = ["feature", "importance"]

print(f"\n=== [Table] Top 10 Important Features ({best_model_name}) ===")
print(feat_imp_top.to_string(index=False))
feat_imp_top.to_csv(TABLE_DIR / "top_feature_importance.csv", index=False)

plt.figure(figsize=(8, 4))
feat_imp.head(top_k).plot(kind="barh")
plt.gca().invert_yaxis()
plt.xlabel("Feature importance")
plt.title(f"Top 10 important features ({best_model_name})")
plt.tight_layout()
save_current_figure("top_feature_importance.png")

# =============================================================================
# 11. 최종 요약
# =============================================================================

print("\n" + "="*80)
print("11. 최종 요약")
print("="*80)

print("\n[핵심 요약]")
print("  • Train/Test: 2020–2023 학습, 2024 테스트 (시계열 누수 방지)")
print("  • 타깃 변환: log1p(daily_visitors)로 학습 → expm1으로 복원 후 평가")
print("  • RF 파라미터 비교: RandomizedSearchCV 대신, 소수 후보 조합을 직접 비교(표/그래프)")

print("\n[Baseline]")
print(f"  • MSE: {baseline_mse:,.1f} | R²: {baseline_r2:.4f} | MAE: {baseline_mae:,.1f}")

print("\n[Random Forest default vs sweep_best (Test 2024)]")
rf_def = results["Random Forest (default)"]
rf_best = results["Random Forest (sweep_best)"]

print(f"  • RF default   - MSE: {rf_def['MSE_test']:,.1f} | R²: {rf_def['R2_test']:.4f} | MAE: {rf_def['MAE_test']:,.1f}")
print(f"  • RF sweep_best- MSE: {rf_best['MSE_test']:,.1f} | R²: {rf_best['R2_test']:.4f} | MAE: {rf_best['MAE_test']:,.1f}")
print(f"  • Best RF overall: {best_model_name}")

print("\n" + "="*80)
print("분석 완료")
print("="*80)
